name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version type (auto-detects from package.json if not specified)"
        required: false
        type: choice
        options:
          - ""
          - patch
          - minor
          - major

permissions:
  id-token: write # Required for OIDC

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Need full history for release-it

      # setup-node configures auth with registry-url and NODE_AUTH_TOKEN
      # See: https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org/"

      - name: Set up SSH signing
        uses: photostructure/git-ssh-signing-action@7a06ef30090b6755c6c9a4295e8afd95bf264bc1 # v1.0.0
        with:
          ssh-signing-key: ${{ secrets.SSH_SIGNING_KEY }}
          git-user-name: ${{ secrets.GIT_USER_NAME }}
          git-user-email: ${{ secrets.GIT_USER_EMAIL }}

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm run release -- --ci ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
