name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version type (auto-detects from package.json if not specified)"
        required: false
        type: choice
        options:
          - ""
          - patch
          - minor
          - major

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for release-it to create tags/commits

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Need full history for release-it

      # setup-node with registry-url is required for OIDC trusted publishing
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Set up SSH signing
        uses: photostructure/git-ssh-signing-action@a770c2ff3aea31d9df9f2974ac9d672f2bfe62f3 # v1.1.0
        with:
          ssh-signing-key: ${{ secrets.SSH_SIGNING_KEY }}
          git-user-name: ${{ secrets.GIT_USER_NAME }}
          git-user-email: ${{ secrets.GIT_USER_EMAIL }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Release with release-it
        run: npm run release -- --ci ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
