name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version type (auto-detects from package.json if not specified)"
        required: false
        type: choice
        options:
          - ""
          - patch
          - minor
          - major

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for release-it to create tags/commits

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Need full history for release-it

      # setup-node with registry-url is required for OIDC trusted publishing
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Set up SSH signing
        uses: photostructure/git-ssh-signing-action@7a06ef30090b6755c6c9a4295e8afd95bf264bc1 # v1.0.0
        with:
          ssh-signing-key: ${{ secrets.SSH_SIGNING_KEY }}
          git-user-name: ${{ secrets.GIT_USER_NAME }}
          git-user-email: ${{ secrets.GIT_USER_EMAIL }}

      - name: Update npm to latest version  
        run: npm install -g npm@latest

      - name: Check npm configuration
        run: |
          npm version
          npm config list
          npm whoami 2>/dev/null || echo "Not logged in (expected with OIDC)"
          echo "NODE_AUTH_TOKEN set: ${NODE_AUTH_TOKEN:+yes}"
          echo "NPM_CONFIG_USERCONFIG: $NPM_CONFIG_USERCONFIG"

      - name: Install dependencies
        run: npm ci

      - name: Test npm publish (dry run)
        run: npm publish --dry-run
        continue-on-error: true

      - name: Release
        run: npm run release -- --ci ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
